# Generated by Django 6.0.7 on 2026-07-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
